Feature/90
MetaCell/salk-interactive-atlas pull request #110
Opened 2022-05-06 09:11 UTC by afonsobspinto

Closes #

Implemented solution: ... 

How to test this PR: ...

### Sanity checks:
- [ ] The pull request is explicitly linked to the relevant issue(s)
- [ ] The issue is well described: clearly states the problem and the general proposed solution(s)
- [ ] From the issue and the current PR it is explicitly stated how to test the current change
- [ ] The labels in the issue set the scope and the type of issue (bug, feature, etc.)
- [ ] All the automated test checks are passing
- [ ] All the linked issues are included in one milestone
- [ ] All the linked issues are assigned

### Breaking changes (select one):
- [ ] The present changes do not change the preexisting api in any way
- [ ] This PR and the issue are tagged as a `breaking-change`

### Possible deployment updates issues (select one):
- [ ] There is no reason why deployments may break after the current update
- [ ] This PR and the issue are tagged as `alert:deployment`

### Test coverage (select one):
- [ ] Tests for the relevant cases are included in this pr
- [ ] The changes included in this pr are out of the current test coverage scope

### Documentation (select one):
- [ ] The documentation has been updated to match the current changes
- [ ] The changes included in this PR are out of the current documentation scope

### Nice to have (if relevant):
- [ ] Screenshots of the changes
- [ ] Explanatory video/animated gif

2022-05-06 09:17 UTC, afonsobspinto commented
Use this instead of the attribute in the model: https://www.django-rest-framework.org/api-guide/fields/#serializermethodfield
Make the field boolean has_edit_experiment_permission

2022-05-08 18:17 UTC, zsinnema requested changes

2022-05-08 18:17 UTC, zsinnema commented on applications/workspaces/backend/api/models/experiment.py
> +class ExperimentPermissions(models.TextChoices):
@afonsobspinto do we still need this?

2022-05-10 06:46 UTC, zsinnema commented
@afonsobspinto can you please resolve the merge conflict? Thanks

2022-05-10 10:09 UTC, merged